### ISSUE TITLE
Revisar buscador

### ISSUE THREAD

**Issue by NikkiAsteinza** [NikkiAsteinza/giasa-app#2]
- [x] El buscador funciona en todas las paginas
- [x] Añadir mensaje de info sobre pulsar enter para buscar
- [x] Añadir feedback no elementos encontrados

**Comment by NikkiAsteinza** [comment]
Por fi abre rama para añadir el mensaje de info sobre pulsar enter. Puedes usar el mismo que el de no se han encontrado datos.

**Comment by GaleGizmo** [comment]
Hecho, revisa cuando puedas
